import pandas as pd
import numpy as np
import joblib
import argparse

def norm(s):
    return str(s).strip().lower().replace(" ", "_").replace("-", "_")

def main():
    parser = argparse.ArgumentParser(description="Predict prices using a trained model (RF or XGBoost)")
    parser.add_argument("--model", type=str, choices=["rf", "xgb"], default="rf", 
                        help="Which model to use for prediction: 'rf' (Random Forest) or 'xgb' (XGBoost). Default is 'rf'.")
    args = parser.parse_args()

    # 1. Read the sensitivity.csv generated by the analysis pipeline
    print("Loading sensitivity.csv...")
    try:
        sens_df = pd.read_csv("sensitivity.csv")
    except FileNotFoundError:
        print("Error: 'sensitivity.csv' not found. Please run the analysis pipeline first (cli.py run ...)")
        return
        
    print(f"Loaded {len(sens_df)} rows for prediction.")

    # 2. Load the Best Model and its required features based on argument
    if args.model == "xgb":
        model_file = "best_xgb_model.pkl"
        features_file = "xgb_features.pkl"
        medians_file = "xgb_medians.pkl"
        model_name = "XGBoost"
    else:
        model_file = "best_rf_model.pkl"
        features_file = "rf_features.pkl"
        medians_file = "rf_medians.pkl"
        model_name = "Random Forest"

    try:
        model = joblib.load(model_file)
        features = joblib.load(features_file)
        medians = joblib.load(medians_file)
        print(f"\nSuccessfully loaded the trained {model_name} model.")
    except FileNotFoundError:
        print(f"Error: Model files not found. Please run 'python3 {'xgboost_model.py' if args.model == 'xgb' else 'random_forest.py'}' first to generate them.")
        return

    # 3. Data Alignment: Build prediction matrix matching exactly what the RF model expects
    X_pred = pd.DataFrame(columns=features)
    
    for i, row in sens_df.iterrows():
        # Start by filling the row with the training data medians (Neutral Baseline)
        X_pred.loc[i] = medians[features].values
        
        # Zero out typical one-hot encoded columns (assuming median=0 for categorical)
        # This prevents 'ghost' categories from bleeding into our targeted predictions
        for f in features:
            if medians[f] in [0, 1] and "_" in f:
                X_pred.loc[i, f] = 0

        # Map sensitivity row values to the model's specific one-hot feature space
        for col in sens_df.columns:
            if col == "price":
                continue
                
            val = row[col]
            norm_col = norm(col)
            norm_val = norm(val)
            
            # Construct what the one-hot column SHOULD look like
            expected_feature = f"{norm_col}_{norm_val}"
            
            # Print debug info to see what we're looking for
            # print(f"Looking for: {expected_feature}")
            
            # 1. Exact match (e.g., brand_name_havit)
            if expected_feature in features:
                X_pred.loc[i, expected_feature] = 1
            
            # 2. NLP Match (e.g., 'ANC' maps to 'nlp_anc')
            elif f"nlp_{norm_val}" in features:
                X_pred.loc[i, f"nlp_{norm_val}"] = 1
                
            # 3. Handle specific continuous/numeric features (waterproof_standard, battery_life)
            elif norm_col in features:
                try:
                    # Specific handler for waterproof standard (IPX-5 -> 5.0)
                    if "ipx" in norm_val:
                        num_val = float(norm_val.replace("ipx", "").replace("_", "").replace("-", ""))
                        X_pred.loc[i, norm_col] = num_val
                        
                    # Specific handler for battery life (e.g. "3-5 hours" -> 4.0, "more than 20 hours" -> 20.0)
                    elif "hour" in norm_val or "hr" in norm_val:
                        import re
                        nums = re.findall(r'\d+', norm_val)
                        if len(nums) == 2:
                            num_val = (float(nums[0]) + float(nums[1])) / 2.0
                        elif len(nums) == 1:
                            num_val = float(nums[0])
                        else:
                            num_val = medians[norm_col]
                        X_pred.loc[i, norm_col] = num_val
                        
                    # Fallback generic float conversion
                    else:
                        num_val = float(val)
                        X_pred.loc[i, norm_col] = num_val
                except ValueError:
                    pass
                    
            # 4. Fallback to "Other" or "No_Specific" for categorical columns
            else:
                # Value wasn't in training data. Fall back to "Other" or "No_Specific"
                fallback_other = f"{norm_col}_other"
                fallback_no = f"{norm_col}_no_specific"
                
                if fallback_other in features:
                    X_pred.loc[i, fallback_other] = 1
                elif fallback_no in features:
                    X_pred.loc[i, fallback_no] = 1

    # 4. Predict Prices
    print(f"\nPredicting prices using {model_name}...")
    
    if args.model == "xgb":
        # XGBoost was trained on raw prices with squaredlogerror, no need to expm1
        y_pred = model.predict(X_pred)
    else:
        # Random Forest was trained on log(price), reverse it with expm1
        y_pred_log = model.predict(X_pred)
        y_pred = np.expm1(y_pred_log)
        
    sens_df["predicted_price"] = y_pred.round(2)
    
    # 5. Evaluate Acceptance Criteria
    # absolute difference <= $2.00 gets 1 (Accepted), else 0 (Rejected)
    sens_df.loc[:, "acceptance"] = (abs(sens_df["predicted_price"] - sens_df["price"]) <= 2.0).astype(int)
    
    # 6. Save final results
    sens_df.to_csv("result.csv", index=False)
    print("\nFinal Comparison:")
    print(sens_df.to_string())
    print("\nResults saved successfully to 'result.csv'.")

if __name__ == "__main__":
    main()